# Generated by Django 5.2.3 on 2026-01-03 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0004_alter_video_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='description',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
