# Generated by Django 5.2.3 on 2026-01-03 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0005_video_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='name',
            new_name='title',
        ),
    ]
