# Generated by Django 5.2.3 on 2026-01-03 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0006_rename_name_video_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='category',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='video',
            name='thumbnail',
            field=models.FileField(blank=True, upload_to='thumbnails/'),
        ),
        migrations.AlterField(
            model_name='video',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
