# Generated by Django 5.2.3 on 2026-01-05 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0008_alter_video_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='thumbnail',
            new_name='thumbnail_url',
        ),
    ]
