# Generated by Django 5.2.3 on 2026-01-06 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0010_remove_video_thumbnail_url_video_thumbnail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='hls_base_path',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='file',
            field=models.FileField(blank=True, upload_to='videos/', verbose_name='Original File'),
        ),
    ]
