# Generated by Django 5.2.3 on 2026-01-06 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0011_video_hls_base_path_alter_video_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='hls_base_path',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='HLS Base Path'),
        ),
    ]
