# Generated by Django 5.2.3 on 2026-01-06 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0012_alter_video_hls_base_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='thumbnail',
            field=models.FileField(blank=True, upload_to='thumbnails/'),
        ),
    ]
