# Generated by Django 5.2.3 on 2026-01-08 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0014_alter_video_category_alter_video_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='thumbnail',
            field=models.FileField(blank=True, editable=False, null=True, upload_to='thumbnails/'),
        ),
    ]
