# Generated by Django 5.2.3 on 2025-07-27 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_clientuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientuser',
            name='has_verified_email',
            field=models.BooleanField(default=False),
        ),
    ]
