# Generated by Django 5.2.3 on 2025-09-11 21:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_activationtoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activationtoken',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 12, 21, 2, 57, 111018, tzinfo=datetime.timezone.utc)),
        ),
    ]
