# Generated by Django 5.2.3 on 2025-09-23 09:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_activationtoken_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activationtoken',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 24, 9, 16, 46, 877445, tzinfo=datetime.timezone.utc)),
        ),
    ]
