# Generated by Django 5.2.3 on 2025-10-26 16:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_activationtoken_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activationtoken',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 27, 16, 0, 50, 556728, tzinfo=datetime.timezone.utc)),
        ),
    ]
