# Generated by Django 5.2.3 on 2025-11-27 20:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_activationtoken_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activationtoken',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 28, 20, 50, 32, 451832, tzinfo=datetime.timezone.utc)),
        ),
    ]
