# Generated by Django 5.2.3 on 2025-11-27 21:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_alter_activationtoken_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activationtoken',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 28, 21, 11, 54, 32322, tzinfo=datetime.timezone.utc)),
        ),
    ]
