# Generated by Django 5.2.3 on 2025-11-29 12:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_alter_activationtoken_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activationtoken',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 30, 12, 54, 19, 724441, tzinfo=datetime.timezone.utc)),
        ),
    ]
