# Generated by Django 5.2.3 on 2025-11-29 12:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_alter_activationtoken_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activationtoken',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 30, 12, 58, 0, 540799, tzinfo=datetime.timezone.utc)),
        ),
    ]
