# Generated by Django 5.2.3 on 2025-12-27 09:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_alter_activationtoken_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activationtoken',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 12, 28, 9, 12, 9, 21450, tzinfo=datetime.timezone.utc)),
        ),
    ]
