# Generated by Django 5.2.3 on 2026-01-01 21:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_alter_activationtoken_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activationtoken',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 2, 21, 34, 7, 549959, tzinfo=datetime.timezone.utc)),
        ),
    ]
