# Generated by Django 5.2.3 on 2026-01-03 09:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_alter_activationtoken_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activationtoken',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 4, 9, 2, 19, 40639, tzinfo=datetime.timezone.utc)),
        ),
    ]
