# Generated by Django 5.2.3 on 2026-01-03 18:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_alter_activationtoken_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activationtoken',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 4, 18, 43, 2, 698846, tzinfo=datetime.timezone.utc)),
        ),
    ]
