# Generated by Django 5.2.3 on 2026-01-05 14:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0042_alter_activationtoken_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activationtoken',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 6, 14, 15, 56, 630884, tzinfo=datetime.timezone.utc)),
        ),
    ]
