# Generated by Django 5.2.3 on 2026-01-06 14:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0043_alter_activationtoken_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activationtoken',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 7, 14, 28, 36, 419669, tzinfo=datetime.timezone.utc)),
        ),
    ]
