# Generated by Django 5.2.3 on 2026-01-06 15:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0046_alter_activationtoken_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activationtoken',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 7, 15, 29, 19, 949918, tzinfo=datetime.timezone.utc)),
        ),
    ]
