# Generated by Django 5.2.3 on 2026-01-06 16:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0057_alter_activationtoken_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activationtoken',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 7, 16, 39, 55, 447059, tzinfo=datetime.timezone.utc)),
        ),
    ]
