# Generated by Django 5.2.3 on 2026-01-06 19:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0058_alter_activationtoken_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activationtoken',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 7, 19, 57, 36, 323527, tzinfo=datetime.timezone.utc)),
        ),
    ]
