# Generated by Django 5.2.3 on 2026-01-06 22:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0069_alter_activationtoken_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activationtoken',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 7, 22, 6, 59, 898615, tzinfo=datetime.timezone.utc)),
        ),
    ]
