# Generated by Django 5.2.3 on 2026-01-08 21:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0074_alter_activationtoken_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activationtoken',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 9, 21, 41, 25, 108863, tzinfo=datetime.timezone.utc)),
        ),
    ]
