# Generated by Django 5.2.3 on 2026-01-10 19:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0092_alter_activationtoken_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activationtoken',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 11, 19, 43, 52, 446793, tzinfo=datetime.timezone.utc)),
        ),
    ]
